/**
 * Automation Suggester — generates specific, actionable automation suggestions
 * referencing real device parameters found on the user's tracks.
 *
 * Pure function module: no SDK calls, no side effects.
 *
 * For contrast gaps: suggests up to 3 parameters per gap.
 * For transition points: suggests up to 2 parameters per transition.
 *
 * Prioritizes filter parameters, suppresses already-automated params,
 * and falls back to generic mixer suggestions when needed.
 */
import type { ContrastGapIssue } from "./contrast-gap-detector.js";
import type { ParameterInventoryEntry } from "./parameter-scanner.js";
import type { AlsAutomationData, SectionAutomationSummary } from "./als-parser.js";

// ─── Exported Types ────────────────────────────────────────────────────

/** A single automation suggestion generated by the module. */
export interface AutomationSuggestion {
  readonly trackName: string;
  readonly deviceName: string;
  readonly parameterName: string;
  readonly pattern: string;
  readonly sectionIds: readonly string[];
  readonly type: "contrast_gap" | "transition";
}

/** A transition point between two adjacent sections. */
export interface TransitionPoint {
  readonly fromSectionId: string;
  readonly toSectionId: string;
  readonly energyDelta: number;
}

/** Input data for the automation suggester. */
export interface AutomationSuggesterInput {
  readonly contrastGaps: readonly ContrastGapIssue[];
  readonly transitionPoints: readonly TransitionPoint[];
  readonly parameterInventory: readonly ParameterInventoryEntry[];
  readonly automationData: AlsAutomationData | null;
  readonly sectionAutomationMap: ReadonlyMap<string, SectionAutomationSummary[]> | null;
  readonly activeTracks: ReadonlyMap<string, readonly string[]>;
  readonly genre: string | null;
}

// ─── Constants ─────────────────────────────────────────────────────────

/** Maximum suggestions per contrast gap. */
const MAX_SUGGESTIONS_PER_GAP = 3;

/** Maximum suggestions per transition point. */
const MAX_SUGGESTIONS_PER_TRANSITION = 2;

/** Device name patterns that indicate filter-type devices (prioritized). */
const FILTER_DEVICE_PATTERNS = ["filter", "eq", "auto filter"];

/** Parameter names excluded from suggestions. */
const EXCLUDED_PARAMETER_NAMES = ["Device On"];

/**
 * Parameter names considered "transition-relevant" — only these are eligible
 * for transition suggestions.
 */
const TRANSITION_RELEVANT_PATTERNS = [
  "filter freq",
  "frequency",
  "cutoff",
  "resonance",
  "send",
  "volume",
  "pan",
  "lfo rate",
  "lfo speed",
  "chorus",
  "depth",
  "decay",
  "release",
  "attack",
  "dry/wet",
];

/** Automation patterns for contrast gap suggestions. */
const GAP_PATTERNS = [
  "gradual_sweep",
  "subtle_variation",
  "rhythmic_modulation",
];

/** Automation patterns for transition suggestions. */
const TRANSITION_PATTERNS = [
  "build_release",
  "filter_sweep",
  "volume_swell",
];

/** Fallback generic mixer parameters when no suitable device params found. */
const GENERIC_MIXER_PARAMS: readonly { deviceName: string; parameterName: string }[] = [
  { deviceName: "Mixer", parameterName: "Track Volume" },
  { deviceName: "Mixer", parameterName: "Track Pan" },
];

// ─── Internal Helpers ──────────────────────────────────────────────────

/**
 * Check if a device name matches filter-priority patterns.
 */
function isFilterDevice(deviceName: string): boolean {
  const lower = deviceName.toLowerCase();
  return FILTER_DEVICE_PATTERNS.some((pattern) => lower.includes(pattern));
}

/**
 * Check if a parameter name is transition-relevant.
 */
function isTransitionRelevant(parameterName: string): boolean {
  const lower = parameterName.toLowerCase();
  return TRANSITION_RELEVANT_PATTERNS.some((pattern) => lower.includes(pattern));
}

/**
 * Check if a parameter should be excluded from suggestions.
 * Excludes: "Device On", parameters with min === max.
 */
function isExcludedParameter(entry: ParameterInventoryEntry): boolean {
  if (EXCLUDED_PARAMETER_NAMES.includes(entry.parameterName)) {
    return true;
  }
  if (entry.min === entry.max) {
    return true;
  }
  return false;
}

/**
 * Check if a parameter is already automated in the given sections.
 *
 * A parameter is considered "already automated" if any of the relevant sections
 * have an active automation envelope for the same track (by trackIndex).
 *
 * When automationData is available and sectionAutomationMap is provided, we check
 * if the track has active envelopes with the same parameter name in those sections.
 */
function isAlreadyAutomated(
  entry: ParameterInventoryEntry,
  sectionIds: readonly string[],
  automationData: AlsAutomationData | null,
  sectionAutomationMap: ReadonlyMap<string, SectionAutomationSummary[]> | null,
): boolean {
  if (!automationData || !sectionAutomationMap) {
    return false;
  }

  // Check if this specific parameter has automation in any of the relevant sections
  // We match by checking if the track has any active automation envelope whose
  // resolved parameterName matches this entry's parameterName and deviceName
  for (const sectionId of sectionIds) {
    const summaries = sectionAutomationMap.get(sectionId);
    if (!summaries) continue;

    // Check if this track has active automation in this section
    const trackSummary = summaries.find((s) => s.trackIndex === entry.trackIndex);
    if (!trackSummary || trackSummary.activeEnvelopeCount === 0) continue;

    // Additionally check the raw envelopes for a match on device+parameter name
    for (const envelope of automationData.envelopes) {
      if (
        envelope.trackIndex === entry.trackIndex &&
        envelope.deviceName === entry.deviceName &&
        envelope.parameterName === entry.parameterName
      ) {
        // Check if this envelope has activity in this section's range
        // (we already know the track has active envelopes in this section)
        return true;
      }
    }
  }

  return false;
}

/**
 * Get parameters available for a set of sections, filtered by active tracks
 * and excluding already-automated and excluded params.
 */
function getAvailableParams(
  sectionIds: readonly string[],
  inventory: readonly ParameterInventoryEntry[],
  activeTracks: ReadonlyMap<string, readonly string[]>,
  automationData: AlsAutomationData | null,
  sectionAutomationMap: ReadonlyMap<string, SectionAutomationSummary[]> | null,
): ParameterInventoryEntry[] {
  // Collect active track names across all relevant sections
  const activeTrackNames = new Set<string>();
  for (const sectionId of sectionIds) {
    const tracks = activeTracks.get(sectionId);
    if (tracks) {
      for (const name of tracks) {
        activeTrackNames.add(name);
      }
    }
  }

  // Filter inventory to active tracks, non-excluded, non-automated
  return inventory.filter((entry) => {
    if (!activeTrackNames.has(entry.trackName)) return false;
    if (isExcludedParameter(entry)) return false;
    if (isAlreadyAutomated(entry, sectionIds, automationData, sectionAutomationMap)) return false;
    return true;
  });
}

/**
 * Sort parameters with filter devices first (prioritized).
 */
function sortByFilterPriority(params: ParameterInventoryEntry[]): ParameterInventoryEntry[] {
  return [...params].sort((a, b) => {
    const aIsFilter = isFilterDevice(a.deviceName) ? 0 : 1;
    const bIsFilter = isFilterDevice(b.deviceName) ? 0 : 1;
    return aIsFilter - bIsFilter;
  });
}

/**
 * Generate fallback generic mixer suggestions for a set of sections.
 */
function generateFallbackSuggestions(
  sectionIds: readonly string[],
  type: "contrast_gap" | "transition",
  activeTracks: ReadonlyMap<string, readonly string[]>,
  maxCount: number,
): AutomationSuggestion[] {
  // Pick the first active track name we can find
  const activeTrackNames = new Set<string>();
  for (const sectionId of sectionIds) {
    const tracks = activeTracks.get(sectionId);
    if (tracks) {
      for (const name of tracks) {
        activeTrackNames.add(name);
      }
    }
  }

  if (activeTrackNames.size === 0) {
    return [];
  }

  const trackName = [...activeTrackNames][0]!;
  const patterns = type === "contrast_gap" ? GAP_PATTERNS : TRANSITION_PATTERNS;
  const suggestions: AutomationSuggestion[] = [];

  for (let i = 0; i < Math.min(maxCount, GENERIC_MIXER_PARAMS.length); i++) {
    const generic = GENERIC_MIXER_PARAMS[i]!;
    suggestions.push({
      trackName,
      deviceName: generic.deviceName,
      parameterName: generic.parameterName,
      pattern: patterns[i % patterns.length]!,
      sectionIds,
      type,
    });
  }

  return suggestions;
}

// ─── Public API ────────────────────────────────────────────────────────

/**
 * Generate specific automation suggestions for contrast gaps and transitions.
 *
 * Logic:
 * 1. For each contrast gap: pick up to 3 parameters from tracks active in
 *    those sections. Prioritize filter params. Suppress already-automated.
 * 2. For each transition point: pick up to 2 parameters from tracks active
 *    in adjacent sections. Only use transition-relevant params.
 * 3. Fall back to generic mixer suggestions when no suitable params found.
 *
 * @param input - All data needed to generate suggestions.
 * @returns Array of automation suggestions.
 */
export function generateAutomationSuggestions(
  input: AutomationSuggesterInput,
): AutomationSuggestion[] {
  const {
    contrastGaps,
    transitionPoints,
    parameterInventory,
    automationData,
    sectionAutomationMap,
    activeTracks,
  } = input;

  const suggestions: AutomationSuggestion[] = [];

  // ─── Contrast Gap Suggestions ──────────────────────────────────────

  for (const gap of contrastGaps) {
    const sectionIds = gap.sectionIds;

    // Get available (non-automated, non-excluded) params for active tracks
    const available = getAvailableParams(
      sectionIds,
      parameterInventory,
      activeTracks,
      automationData,
      sectionAutomationMap,
    );

    // Sort with filter parameters first
    const sorted = sortByFilterPriority(available);

    if (sorted.length === 0) {
      // Fallback to generic mixer suggestions
      const fallback = generateFallbackSuggestions(
        sectionIds,
        "contrast_gap",
        activeTracks,
        MAX_SUGGESTIONS_PER_GAP,
      );
      suggestions.push(...fallback);
      continue;
    }

    // Pick up to MAX_SUGGESTIONS_PER_GAP, assigning patterns cyclically
    const count = Math.min(sorted.length, MAX_SUGGESTIONS_PER_GAP);
    for (let i = 0; i < count; i++) {
      const entry = sorted[i]!;
      suggestions.push({
        trackName: entry.trackName,
        deviceName: entry.deviceName,
        parameterName: entry.parameterName,
        pattern: GAP_PATTERNS[i % GAP_PATTERNS.length]!,
        sectionIds,
        type: "contrast_gap",
      });
    }
  }

  // ─── Transition Suggestions ────────────────────────────────────────

  for (const transition of transitionPoints) {
    const sectionIds = [transition.fromSectionId, transition.toSectionId];

    // Get available params for active tracks in both adjacent sections
    const available = getAvailableParams(
      sectionIds,
      parameterInventory,
      activeTracks,
      automationData,
      sectionAutomationMap,
    );

    // Filter to transition-relevant parameters only
    const transitionRelevant = available.filter((entry) =>
      isTransitionRelevant(entry.parameterName),
    );

    // Sort with filter parameters first
    const sorted = sortByFilterPriority(transitionRelevant);

    if (sorted.length === 0) {
      // Fallback to generic mixer suggestions
      const fallback = generateFallbackSuggestions(
        sectionIds,
        "transition",
        activeTracks,
        MAX_SUGGESTIONS_PER_TRANSITION,
      );
      suggestions.push(...fallback);
      continue;
    }

    // Pick up to MAX_SUGGESTIONS_PER_TRANSITION
    const count = Math.min(sorted.length, MAX_SUGGESTIONS_PER_TRANSITION);
    for (let i = 0; i < count; i++) {
      const entry = sorted[i]!;
      suggestions.push({
        trackName: entry.trackName,
        deviceName: entry.deviceName,
        parameterName: entry.parameterName,
        pattern: TRANSITION_PATTERNS[i % TRANSITION_PATTERNS.length]!,
        sectionIds,
        type: "transition",
      });
    }
  }

  return suggestions;
}
